pus:
  - name: "ПУ-Центральное"
    subdivisions:
      - id: 1101
        pu: "ПУ-Центральное"
        type: "ПОГЗ"
        number: 2
        locality:
          kind: "с."
          name: "Васильки"
        aliases:
          - "ПЗ-2"
          - "ПЗ 2"
          - "ПЗ2"
          - "службой ПЗ-2"
          - "ПОГЗ №2"
          - "ПОГЗ-2"
          - "погз 2"
          - "пограничная застава №2"
          - "пограничная застава в с. Васильки"
          - "ПОГЗ №2 (с. Васильки)"
          - "ПОГЗ №2 в с. Васильки"
      - id: 1102
        pu: "ПУ-Центральное"
        type: "ОПК"
        name: "Центральное"
        locality:
          kind: "г."
          name: "Южный"
        aliases:
          - "ОПК Центральное"
          - "ОПК «Центральное»"
          - "на посту ОПК Центральное"
          - "на посту ОПК «Центральное»"
      - id: 1103
        pu: "ПУ-Центральное"
        type: "ПОГК"
        name: "Лесная"
        locality:
          kind: "пгт"
          name: "Лесной"
        aliases:
          - "ПОГК «Лесная»"
          - "ПОГК Лесная"
          - "в районе ПОГК Лесная"
      - id: 1104
        pu: "ПУ-Центральное"
        type: "ПОГО"
        name: "Южное"
        locality:
          kind: "г."
          name: "Южный"
        aliases:
          - "ПОГО Южное"
          - "пограничный отряд Южное"
      - id: 1105
        pu: "ПУ-Центральное"
        type: "ОПК"
        name: "Заречное"
        locality:
          kind: "г."
          name: "Заречный"
        aliases:
          - "ОПК Заречное"
          - "на посту ОПК Заречное"
      - id: 1106
        pu: "ПУ-Центральное"
        type: "ПОГК"
        name: "Речная"
        locality:
          kind: "пгт"
          name: "Речной"
        aliases:
          - "ПОГК Речная"
          - "в районе ПОГК Речная"
  - name: "ПУ-Северное"
    subdivisions:
      - id: 1201
        pu: "ПУ-Северное"
        type: "ПОГЗ"
        number: 1
        locality:
          kind: "с."
          name: "Полярное"
        aliases:
          - "ПЗ-1"
          - "ПЗ 1"
          - "ПЗ1"
          - "службой ПЗ1"
          - "ПОГЗ №1"
          - "ПОГЗ-1"
          - "погз 1"
          - "пограничная застава №1"
          - "ПОГЗ №1 в с. Полярное"
      - id: 1202
        pu: "ПУ-Северное"
        type: "ПОГК"
        name: "Северная"
        locality:
          kind: "пгт"
          name: "Северный"
        aliases:
          - "ПОГК «Северная»"
          - "ПОГК Северная"
          - "в районе ПОГК Северная"
      - id: 1203
        pu: "ПУ-Северное"
        type: "ОПК"
        name: "Северное"
        locality:
          kind: "г."
          name: "Северск"
        aliases:
          - "ОПК Северное"
          - "на посту ОПК Северное"
      - id: 1204
        pu: "ПУ-Северное"
        type: "ПОГО"
        name: "Тундровое"
        locality:
          kind: "с."
          name: "Тундра"
        aliases:
          - "ПОГО Тундровое"
          - "пограничный отряд Тундровое"
      - id: 1205
        pu: "ПУ-Северное"
        type: "ПОГК"
        name: "Озерная"
        locality:
          kind: "пгт"
          name: "Озерный"
        aliases:
          - "ПОГК Озерная"
          - "в районе ПОГК Озерная"
      - id: 1206
        pu: "ПУ-Северное"
        type: "ОПК"
        name: "Горное"
        locality:
          kind: "г."
          name: "Горный"
        aliases:
          - "ОПК Горное"
          - "на посту ОПК Горное"
  - name: "ПУ-Южное"
    subdivisions:
      - id: 1301
        pu: "ПУ-Южное"
        type: "ПОГЗ"
        number: 3
        locality:
          kind: "с."
          name: "Южные Ключи"
        aliases:
          - "ПЗ-3"
          - "ПЗ 3"
          - "ПЗ3"
          - "ПОГЗ №3"
          - "ПОГЗ-3"
          - "погз 3"
          - "пограничная застава №3"
          - "ПОГЗ №3 в с. Южные Ключи"
      - id: 1302
        pu: "ПУ-Южное"
        type: "ОПК"
        name: "Южное"
        locality:
          kind: "г."
          name: "Южногорск"
        aliases:
          - "ОПК Южное"
          - "на посту ОПК Южное"
      - id: 1303
        pu: "ПУ-Южное"
        type: "ПОГК"
        name: "Прибрежная"
        locality:
          kind: "пгт"
          name: "Береговой"
        aliases:
          - "ПОГК Прибрежная"
          - "в районе ПОГК Прибрежная"
      - id: 1304
        pu: "ПУ-Южное"
        type: "ПОГО"
        name: "Степное"
        locality:
          kind: "с."
          name: "Степное"
        aliases:
          - "ПОГО Степное"
          - "пограничный отряд Степное"
      - id: 1305
        pu: "ПУ-Южное"
        type: "ОПК"
        name: "Цветочное"
        locality:
          kind: "г."
          name: "Цветочный"
        aliases:
          - "ОПК Цветочное"
          - "на посту ОПК Цветочное"
      - id: 1306
        pu: "ПУ-Южное"
        type: "ПОГК"
        name: "Солнечная"
        locality:
          kind: "пгт"
          name: "Солнечный"
        aliases:
          - "ПОГК Солнечная"
          - "в районе ПОГК Солнечная"
